# Generated by Django 4.0.2 on 2022-02-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomodachi', '0004_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='this is the first default message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='tomodachi.AppUser'),
        ),
    ]
