# Generated by Django 4.0.2 on 2022-02-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomodachi', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(default='default/profile-pic.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
